name: saral_vani
description: "Real-time simplified captions for hearing impaired"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # Speech-to-Text and Audio Processing
  # speech_to_text: ^6.6.0
  speech_to_text: ^7.3.0 # latest
  permission_handler: ^11.0.0
  audio_session: ^0.1.16
  flutter_tts: ^3.8.5
  
  # AI and Text Processing
  http: ^1.1.0
  dio: ^5.3.2
  
  # Database and Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.2
  
  # UI and Animations
  lottie: ^2.7.0
  flutter_svg: ^2.0.9
  
  # System Features
  # vibration: ^1.8.4
  vibration: ^3.1.4      # latest
  device_info_plus: ^9.1.1
  
  # Accessibility
  flutter_accessibility_service: ^0.3.0
  
  # Utils
  intl: ^0.18.1
  uuid: ^4.1.0
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  
  assets:
    - assets/animations/
    - assets/models/
    - assets/images/
    - assets/fonts/
  
  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
        - asset: assets/fonts/NotoSans-Bold.ttf
          weight: 700
